### ISSUE TITLE
Inline embedding of <svg> for improved accessibility

### ISSUE THREAD

**Issue by jonsterling** [paolobrasolin/jekyll-antex#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Original problem

Currently, the SVG embedding that we do is not optimal for accessibility. First of all, text is converted into outlines instead of embedded; but this can be fixed by reconfiguring `antex` to call `dvisvgm` with the option `--font-format=woff`, so that's OK. The second issue is that SVGs are embedded into the HTML pages by using an `<img>` tag; unfortunately using this tag hides the structure of the SVG from the DOM.

### Proposed solution

It seems that it will work better if we can directly embed the generated SVG code as an `<svg>` tag rather than embedding the generated file using `<img>`. I have played around a little bit with the Firefox accessibility inspector, and it seems that this option does indeed produce better results.

The results are still highly imperfect, since the process of turning structured mathematics into even vector graphics is quite lossy; but I think it would be better than what we do today.

### Alternatives considered

I haven't thought of any alternatives, but I'm open to ideas :)

**Comment by paolobrasolin** [comment]
This sounds like an excellent idea! 

Initially, `img` embeds were chosen to simplify implementation, reduce file size and avoid duplication of inlined code.

The latter is probably a non-issue: I would expect highly duplicated expressions to also be pretty simple. Furthermore, if we use external fonts instead of converting them, then the footprint should be tiny.

Among [the many ways of embedding SVG](https://vecta.io/blog/best-way-to-embed-svg), inlining is also the only one that applies the page's CSS to the SVG content. That's another plus for me: being able to easily match the colors of math and page body is nice.

Embedded fonts will generate much bigger files; maybe there's a way to use external fonts instead. I'll look into that.

I also have a vague recollection of having to convert text to outlines to get the correct shape metrics consistently, but `dvisvgm` has probably improved in the meantime.

Here's what I need to do:
- [ ] check whether using `--font-format=woff` produces the correct metrics in `fit`/`tfm` files
- [ ] check how big the files get when using embedded fonts
- [ ] think about a way to use external fonts instead of embedded ones
- [ ] provide a configuration flag to enable in-page SVG embedding

**Comment by jonsterling** [comment]
That's a great point about the CSS!

**Comment by paolobrasolin** [comment]
@jonsterling I just released [version `0.8.0`](https://github.com/paolobrasolin/jekyll-antex/blob/main/CHANGELOG.md#080---2022-08-25), which should do the trick.

There's a new boolean option named `inlining` -- you can set it to `true` in your `_config.yml` file under the `antex` namespace, just like all other configurations.

Btw: embedding fonts _will_ make files bigger and using external fonts consistently is very tricky. I'll leave size/performance improvements for future me. In any case, we should have the accessibility improvement you suggested.

Let me know whether that works for you!

**Comment by paolobrasolin** [comment]
> That's a great point about the CSS!

Side note: remember to update your styles. Whatever matched `.antex img` should now also match `.antex svg`.

**Comment by jonsterling** [comment]
Thanks so much!! I've deployed this on both my sheafy sites now.

**Comment by jonsterling** [comment]
I have discovered a slight problem when using this: it looks like an embeddged `<svg>` does not get its own namespace, so the IDs of specific elements inside there can clash if multiple SVGs are inlined in the same page. Because the generate SVGs use the `<use>` tag, this results in incorrect rendering...

It seems that this is a really serious limitation with SVG in HTML --- in fact, so serious that I do not think I understand the use-case at all of the `<svg>` tag in HTML, since I can think of no applications for an `<svg>` tag that you can only use once in a page. However, there seems to be a hack the one could use: https://github.com/iconfu/svg-inject

Any thoughts?

**Comment by jonsterling** [comment]
Prefixing is such a smart idea! Thanks for thinking of it :)

**Comment by jonsterling** [comment]
Thanks for doing this btw, I just got around to deploying it on my math websites and it is working well.
